# Generated by Django 6.1 on 2026-09-03 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('PLACA', 'Placas de Yeso'), ('PERFIL', 'Perfilería'), ('FIJACION', 'Fijaciones y Tornillos'), ('MASILLA', 'Masillas y Cintas')], max_length=20)),
                ('medida_mm', models.CharField(blank=True, max_length=10, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por bulto/unidad comercial', max_digits=10)),
                ('unidad_medida', models.CharField(help_text='Ej: Unidad, Rollo 75m, Balde 32kg, Caja x100', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(default='Mi Empresa Drywall', max_length=100)),
                ('nit_rut', models.CharField(blank=True, max_length=50, null=True)),
                ('leyenda_comercial', models.CharField(default='Soluciones Técnicas de Construcción', max_length=150)),
                ('logo_url', models.CharField(blank=True, help_text='URL o enlace del logo de la empresa', max_length=255, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datosempresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('tipo_estructura', models.CharField(choices=[('MURO_SIMPLE', 'Muro Cara Simple'), ('MURO_DOBLE', 'Muro Doble Cara (Divisorio)'), ('CIELORRASO', 'Cielorraso / Techo Suspendido')], max_length=20)),
                ('tipo_placa', models.CharField(choices=[('ST', 'Estándar (Gris)'), ('RH', 'Resistente Humedad (Verde)'), ('RF', 'Resistente Fuego (Rosa)')], default='ST', max_length=5)),
                ('largo', models.FloatField()),
                ('alto_ancho', models.FloatField()),
                ('medida_perfil', models.CharField(choices=[('35', '35 mm'), ('70', '70 mm'), ('100', '100 mm')], max_length=10)),
                ('puertas', models.IntegerField(default=0)),
                ('ventanas', models.IntegerField(default=0)),
                ('costo_mano_obra_m2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('con_aislacion', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='calculador.proyecto')),
            ],
        ),
    ]
