# Generated by Django 6.1 on 2026-09-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosempresa',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='datosempresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Suba el logo de su empresa', null=True, upload_to='logos/'),
        ),
    ]
